import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";

// import Layout from "../layouts";
import { inject } from "mobx-react";
import { observer } from "mobx-react-lite";
import { DataStore } from "../stores/DataStore";
// import Image from "next/image";

type HomeProps = {
  dataStore?: DataStore;
};

const Home: NextPage = inject("dataStore")(
  observer((props: HomeProps) => {
    const dataStore = props.dataStore!;
    console.log(DataStore);

    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Title>Hello world!</Title>
          <p>{dataStore.title} 👋</p>
          <input
            type="text"
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              dataStore.changeTitle(e.target.value)
            }
          />
        </main>

        <footer>this is footer</footer>
      </div>
    );
  })
);

const Title = styled.h1`
  color: red;
`;

export default Home;
