import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import { Button } from "../components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <Button onClick={() => console.log("works")}>Try me!</Button>
      </main>

      <footer>this is footer</footer>
    </div>
  );
};

export default Home;
